// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCQ1LOS_3xlOJkYppD1cwHB14wUXSMMwJg',
    appId: '1:1082196253830:web:ab45b8a03741f92a948507',
    messagingSenderId: '1082196253830',
    projectId: 'udg-firebase-project',
    authDomain: 'udg-firebase-project.firebaseapp.com',
    storageBucket: 'udg-firebase-project.appspot.com',
    measurementId: 'G-EBTXFVZGK8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCldBtubozZQ25IiswZ61n_ATVKvx-XecM',
    appId: '1:1082196253830:android:3e7281f771974f70948507',
    messagingSenderId: '1082196253830',
    projectId: 'udg-firebase-project',
    storageBucket: 'udg-firebase-project.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCVgfbdxROgWj6lP_9gZLx8vfD_wwYKkn8',
    appId: '1:1082196253830:ios:c5d6c9a24ad58203948507',
    messagingSenderId: '1082196253830',
    projectId: 'udg-firebase-project',
    storageBucket: 'udg-firebase-project.appspot.com',
    iosClientId: '1082196253830-e61jk9urgm0u7d3vkvfigg7el4el6t5a.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCVgfbdxROgWj6lP_9gZLx8vfD_wwYKkn8',
    appId: '1:1082196253830:ios:c5d6c9a24ad58203948507',
    messagingSenderId: '1082196253830',
    projectId: 'udg-firebase-project',
    storageBucket: 'udg-firebase-project.appspot.com',
    iosClientId: '1082196253830-e61jk9urgm0u7d3vkvfigg7el4el6t5a.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebase',
  );
}
